### PR TITLE
Ink smart contracts tooling

### PR DESCRIPTION
**Pull request by fersirni**
# **Ink! Explorer**

## **Project description**

Ink Explorer is an application that provides Ink contracts related information on Substrate based blockchains. It subscribes to blockchain and Ink modules events and store the information on its own Mongo database. The backend exposes an API that can interact with the DB and run fast queries to get specific information in a short time.

The idea of this project is to have fast way to start a node that can be used as an explorer getting live and old data for specific contracts or addresses.

This project serves useful information that is not available anywhere else. Since the back end is in charge of obtaining information related to the balances, transactions and more, of the contracts that use Ink modules. Ink Explorer uses polkadot.js to communicate with the Substrate / Polkadot networks. It is safe to say that this project is a must.

Blockcoders is a team that is always contributing to blockchain projects to help the growth of the ecosystem.

The new feature added to this project is a way to deploy WebAssembly smart contracts on any Substrate-based blockchain. This feature is very useful for developers who want to deploy their smart contracts on any Substrate-based blockchain. This feature is very useful for developers who want to deploy their smart contracts on any Substrate-based blockchain. 

### **Why Polkadot?**

Polkadot is a Substrate-based blockchain that allows the creation of multiple parachains to be connected to the main chain. Substrate is a framework that allows the creation of blockchains using a modular approach. It uses Rust programming language and it is very secure. It is also very fast and scalable. Fees in polkadot are very low and the TPS is very high.

**Astar**

The network supports the building of dApps with EVM and WASM smart contracts and offers developers true interoperability, with cross-consensus messaging (XCM). Astar Network focuses on making the best smart contract platform so that dApps developers on Polkadot do not need to pay much attention to infrastructure and can focus more on their dApp.

### References

https://github.com/w3f/Grants-Program/blob/master/applications/ink-explorer.md

This project was originally supported by the Web3 Foundation and the Polkadot team. The project was developed by the BlockCoders team.
As we continue to develop the project, we will continue to support the Astar Network.
We added this new feature to the project, which is the ability to deploy WebAssembly smart contracts on any Substrate-based blockchain.

## Contact information

**Telegram:** https://t.me/blockcoderstg

**Twitter:** https://twitter.com/blockcoders_

**website:** https://blockcoders.io/

**Github:** https://github.com/blockcoders

**Email:** hello@blockcoders.io

## Name of bounty you participated

WebAssemply dApps - https://github.com/AstarNetwork/AstarBounties/issues/15

## Provide a way to access the project for judging and testing by including all links

**PR with new feature:** https://github.com/blockcoders/ink-substrate-explorer-frontend/pull/11/files

**Github - Frontend:** https://github.com/blockcoders/ink-substrate-explorer-frontend

**Github - Backend:** https://github.com/blockcoders/ink-substrate-explorer-api

**Link to hosted dApp:** https://ink-explorer.blockcoders.io/en/blocks

## Must have an open-source license

MIT

## A video explaining your submission

https://www.youtube.com/watch?v=baj8m97cKw8&ab_channel=BlockCodersWeb3

### CODE REVIEW

**Comment by sugurujames** [comment]
@fersirni 
Thank you for your submission!
Is this from Polkadot Latam Hackathon?

**Comment by fersirni** [comment]
@SUGURUSEO It is actually a new feature on a prodcut that we developed for the web3 foundation.

**Comment by fiexer** [comment]
> 

This is under a grant proposal of W3F?
Could you share the link to the proposal.

**Comment by fersirni** [comment]
Here is the link! 
https://github.com/w3f/Grants-Program/pull/1052

**Comment by fiexer** [comment]
> We added this new feature to the project, which is the ability to deploy WebAssembly smart contracts on any Substrate-based blockchain.

Because the solution is aiming to all Substrate blockchains supporting the contract pallet and already receiving a grant from W3F with the vision. We from Astar cant give a separate grant because its already part of the W3F milestones.

Please reach out to me on Telegram to discuss other possibilities on how Astar can support your development and supporting our network. TG: @maartenhenskens

**Pull request closed without merging**
