### PR TITLE
Astar XCM Bounty proposal: Polkadot Hackathon Latam.

### PR DESCRIPTION
**Pull request by dudo50**
- Added Overview ✅
- Added Github repo ✅
- Added Heroku deploy ✅
- Added video ✅
Our bounty proposal is now finished ✍

### CODE REVIEW

**Comment by dudo50** [comment]
https://github.com/AstarNetwork/AstarBounties/issues/16

**Comment by dudo50** [comment]
The Astarot Bounty application proposal for https://github.com/AstarNetwork/AstarBounties/issues/16 is now finished 🎈.

**Comment by dudo50** [comment]
@fiexer @SUGURUSEO , can you please give me suggestions for the project? I would love to make it bounty compliant if it isn't yet quite what you were looking for. Thanks!

**Review by sugurujames — COMMENTED** [review]
Thank you for your submission. We love your product!

After our careful review, our judgement is as follows:

In total 30%
-Contribution to the Astar ecosystem 5%
-Originality, Creativity, and Innovation 5%
-Technical Difficulty 7.5%
-User Experience 12.5%
-Reason The idea is simple and already implemented in Astar portal. The technical difficulty is low since it is mostly straightforward frontend work.

We hope you would continue building this product and love to support if necessary!

**Comment by sugurujames** [comment]
We close this PR as we already formed a TG group for communications

**Pull request closed without merging**
